dwitter/urls.py
# dwitter/urls.py

from django.urls import path
from django.urls import reverse_lazy
from .views import dashboard, profile_list,profile,signup,userlogin,base,afterlogin_view,adddweet
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.views import ( 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from chatApp.views import chating


app_name = "dwitter"

urlpatterns = [
    path("", base, name="base"),
    path("dashboard", dashboard, name="dashboard"),
    path("afterlogin", afterlogin_view, name="afterlogin"),
    path("profile_list/", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
    path("signup",signup,name="signup"),
    path("userlogin",LoginView.as_view(template_name='dwitter/userlogin.html'),name="userlogin"),
    path("userlogout",LogoutView.as_view(template_name='base.html'),name="logout"),
    path('password_reset/', 
        PasswordResetView.as_view(
            template_name='dwitter/password_reset.html',
            html_email_template_name='dwitter/password_reset_email.html'
        ),
        
        name='password_reset'
    ),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='dwitter/password_reset_done.html'),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='dwitter/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(template_name='dwitter/password_reset_complete.html'),name='password_reset_complete'),
    
    path('adddweet',adddweet,name="adddweet"),
    
    
    
]

social/urls.py
from django.contrib import admin
from django.urls import path,include
from chatApp.views import chating,group_chat,createGroup
from videoApp.views import lobby,room,getToken

urlpatterns = [
    path('', include("dwitter.urls")),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    #Chat
    path('chating/',chating,name='chating'),
    path('group/',group_chat,name='group_chat'),
    #~~~~~~
    path('lobby',lobby,name="lobby"),
    path('room/',room,name="room"),
    path('getToken/',getToken,name="get_token"),
    path('creategroup/',createGroup,name="createGroup")
    
]

dwitter/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
    )
    dob=models.DateField(blank=True,null=True)
    bio=models.CharField(max_length=50)
    profile_pic= models.ImageField(upload_to='static/profile_pic/userprofilepic/',null=True,blank=True)
    is_online=models.BooleanField(default=False)
    def __str__(self):
        return self.user.username
    
@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        #Profile.objects.create(user=instance)
        user_profile=Profile(user=instance) 
        user_profile.save()
        print("success")
        user_profile.follows.add(user_profile)
        user_profile.save()
        
class Dweet(models.Model):
    user = models.ForeignKey(
        User, related_name="dweets", on_delete=models.DO_NOTHING
    )
    title= models.CharField(max_length=100)
    post= models.ImageField(upload_to='static/post/',null=True,blank=True)
    body = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    likedby = models.ManyToManyField(User,related_name="likes",blank=True)
    
    def __str__(self):
        return (
            f"{self.user} "
            f"({self.created_at:%Y-%m-%d %H:%M}): "
            f"{self.body[:30]}..."
        )


class Comment(models.Model):
    dweet=models.ForeignKey(Dweet,related_name="comments",on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name="comments", on_delete=models.DO_NOTHING
    )
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return (
            f"{self.user} "
            f"({self.created_at:%Y-%m-%d %H:%M}): "
            f"{self.body[:30]}..."
        )

dwitter/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class SignUpForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','email','username','password']
        widgets = {
        'password': forms.PasswordInput()
        }
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model=models.Profile
        fields=['dob','bio','profile_pic']
        widgets = {
    'dob': forms.DateInput(
        format=('%Y-%m-%d'),
        attrs={'class': 'form-control', 
               'placeholder': 'Select a date',
               'type': 'date'
              }),
}
        
class DweetForm(forms.ModelForm):
    class Meta:
        model=models.Dweet
        fields=['body','post','title']
        widgets = {
        'body': forms.Textarea(attrs={'rows': 3, 'cols': 30})
        }
        


class CommentForm(forms.Form):
    dweetid=  forms.CharField(max_length=20)
    body = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'cols': 30}))

dwitter/views.py
# dwitter/views.py

from django.shortcuts import render,redirect
from .models import Profile,Dweet,Comment
from django.contrib.auth.decorators import login_required
from . import forms,models
from django.http import HttpResponseRedirect,HttpResponse
from django.dispatch import receiver
from django.contrib.auth.signals import user_logged_in,user_logged_out
from django.contrib.auth.models import User


@receiver(user_logged_in)
def got_online(sender,user,request,**kwargs):
    print(user)
    """user.profile.is_online = True
    user.save()"""
    curruser=Profile.objects.get(user=user)
    curruser.is_online=True
    curruser.save()
    
    print("HEllo",user.profile.is_online,user.username,curruser.is_online)

@receiver(user_logged_out)
def got_offline(sender,user,request,**kwargs):
    curruser=Profile.objects.get(user=user)
    curruser.is_online=False
    curruser.save()
    print("bye")
    print("bye",user.profile.is_online,user.username,curruser.is_online)
    

def signup(request):
    profiles=Profile.objects.all()
    usernames=[x.user.username for x in profiles]
    
    userForm=forms.SignUpForm()
    profileForm=forms.ProfileForm()
    mydict={'userForm':userForm,'profileForm':profileForm,'usernames':usernames}
    if request.method=='POST':
        print("post")
        userForm=forms.SignUpForm(request.POST)
        profileForm=forms.ProfileForm(request.POST,request.FILES)
        if userForm.is_valid() and profileForm.is_valid():
            
            user=userForm.save()
            user.set_password(user.password)
            user.save()
            user_profile=Profile.objects.get(user=user)
            print(user_profile)
            print(profileForm.cleaned_data['dob'])
            user_profile.dob=profileForm.cleaned_data['dob']
            user_profile.bio=profileForm.cleaned_data['bio']
            user_profile.profile_pic=profileForm.cleaned_data['profile_pic']
            
            user_profile.save()
            """customer=profileForm.save(commit=False)
            customer.user=user
            customer.save()"""
        else:
            mydict['msg']="A user with that username already exist"
            return render(request,'dwitter/signup.html',context=mydict)

            
    
        return HttpResponseRedirect('userlogin')
    return render(request,'dwitter/signup.html',context=mydict)

def userlogin(request):
    print(request.user)
    return render(request, "dwitter/userlogin.html")
def afterlogin_view(request):
    """curruser=Profile.objects.get(user=request.user)
    curruser.is_online=True
    curruser.save()"""
    return redirect('dashboard')
@login_required()
def dashboard(request):
    if request.method == "POST":
        data = request.POST
        action = data.get("likebtn")
        print(action)
        if action!=None:
            arr=action.split('-')
            did=arr[0]
            act=arr[1]
            dweet=Dweet.objects.get(id=did)
            if act == "like":
                dweet.likedby.add(request.user)
            elif act == "unlike":
                dweet.likedby.remove(request.user)
            dweet.save()
        # create a form instance and populate it with data from the request:
        form = forms.CommentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            #user_profile=Dweet.objects.get(pk=pk)
            #print(user_profile)
            #print("hello")
            #print(Dweet.objects.get(pk=form.cleaned_data['dweetid']))
            comment=Comment.objects.create(dweet=Dweet.objects.get(pk=form.cleaned_data['dweetid']),user=request.user,body=form.cleaned_data['body'])
            #print(form.cleaned_data['body'])
            comment.save()
            # redirect to a new URL:
            return HttpResponseRedirect("dashboard")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.CommentForm()
    print(request.user)
    profiles=Profile.objects.all()
    mails=[x.user.email for x in profiles]
    
    dct={"mails":mails,"form":form}
    return render(request, "dwitter/dashboard.html",context=dct)
@login_required()
def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "dwitter/profile_list.html", {"profiles": profiles})

def base(request):
    if request.user.is_authenticated:
        HttpResponseRedirect('dwitter/dashboard')
    return render(request,"base.html")
@login_required()
def profile(request, pk):
    """below section has to deleted"""
    """if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()"""

    
    
    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    print(profile.is_online,profile.user.username,request.user.username,request.user.profile.is_online)
    return render(request, "dwitter/profile.html", {"profile": profile})

@login_required()
def adddweet(request):
    dweetForm=forms.DweetForm()
    if request.method=='POST':
        dweetForm=forms.DweetForm(request.POST, request.FILES)
        if dweetForm.is_valid():
            dweet=dweetForm.save(commit=False)
            dweet.user=request.user
            dweet.save()
            #dweetForm.save()
            """dweet=Dweet.objects.get(body=dweetForm.cleaned_data['body'])
            print(dweet)
            dweet.user=request.user
            dweet.save()"""
        return HttpResponseRedirect('dashboard')
    
    return render(request, "dwitter/dweet.html",{'dweetForm':dweetForm})


@login_required()
def addComment(request,pk):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = forms.CommentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            #user_profile=Dweet.objects.get(pk=pk)
            #print(user_profile)
            comment=Comment.objects.create(dweet=pk,user=request.user,body=form.cleaned_data['body'])
            print(form.cleaned_data['body'])
            comment.save()
            # redirect to a new URL:
            return HttpResponseRedirect("dashboard")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.CommentForm()

    return render(request, "dashboard.html", {"form": form})

dwitter/templates/dwitter/dashboard.html
<!-- dwitter/templates/dwitter/dashboard.html -->

{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<style>
    

  
      
</style>
<div class="column">
    {% for followed in user.profile.follows.all %}
        {% for dweet in followed.user.dweets.all %}
            <div class="box">
                <div class="title" style="font-size:xxx-large">  {{dweet.title}}</div>
                <div class="title" style="font-size:0.9em; font-weight:400;">  {{ dweet.body }} </div>
               

                <div class="imgclass" style="background-Color:#F5ECAD; height:350px; weight:100%; padding:20px; outline: solid 1px black;
                display: flex;
                justify-content: center; ">
               
                    <img class="img" src="{% static dweet.post.url %}" alt="post pic" style="height:300px; weight:300px;outline: solid 1px black;" >
                </div>    
                  <br>
                

                
                
                <form  method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% render_field form.body class="form-control" placeholder="    Add Your Comment " %}
                    <div class="hidden" style="display:none;">
                    {% render_field form.dweetid class="form-control" value=dweet.id %}
                    </div>
                    <input type="submit" value="Comment">
                </form>

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                <div class="buttons has-addons">
                    {% if request.user in dweet.likedby.all %}
                    <button class="button is-danger" name="likebtn" value="{{dweet.id}}-unlike">
                        Like
                    </button>
                       
                    {% else %}
                    <button class="button is-danger is-light" name="likebtn" value="{{dweet.id}}-like">
                        Like
                    </button>
                        
                        
                    {% endif %}
                </div>

            </form>





                
                <div class="is-small has-text-grey-light" style="float: right ;">
                    {{ dweet.created_at }} by {{ dweet.user.username }}
                </div>
            </div>
        {% endfor %}
    {% endfor %}
</div>
<script>
    
      
</script>
{% endblock content %}

dwitter/templates/dwitter/dweet.html
{% load widget_tweaks %}
<style media="screen">
    a:link {
      text-decoration: none;
    }

    .note {
      text-align: center;
      height: 80px;
      background: #0F2027;  /* fallback for old browsers */
      background: -webkit-linear-gradient(to left, #2C5364, #203A43, #0F2027);  /* Chrome 10-25, Safari 5.1-6 */
      background: linear-gradient(to left, #2C5364, #203A43, #0F2027); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
      color: #fff;
      font-weight: bold;
      line-height: 80px;
    }

    .form-content {
      padding: 5%;
      border: 1px solid #ced4da;
      margin-bottom: 2%;
    }

    .form-control {
      border-radius: 1.5rem;
    }

    .btnSubmit {
      border: none;
      border-radius: 1.5rem;
      padding: 1%;
      width: 20%;
      cursor: pointer;
      background: #009414;
      color: #fff;
    }

    .menu {
      top: 50px;
    }
  </style>

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container register-form">
      <div class="form">
        <div class="note">
          <p>Create a Post</p>
        </div>
        <div class="form-content">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="">Title</label>
                {% render_field dweetForm.title class="form-control" placeholder="Title" %}
              </div>
              <div class="form-group">
                <label for="">Body</label>
                {% render_field dweetForm.post class="form-control" placeholder="Image" %}
              </div>
              <div class="form-group">
                <label for="">Post</label>
                {% render_field dweetForm.body class="form-control" placeholder="    Write your story here" %}
              </div>
  
            </div>
            
          </div>
          <button type="submit" class="btnSubmit">ADD</button>
        </div>
      </div>
    </div>
  </form>

dwitter/templates/dwitter/password_reset.html
{%extends 'base.html'%}

{%block content%}
<div class="center">
	<form method="post" class="card">
		{% csrf_token %}
	    <h2 class="text-center">Reset Password</h2>
		{% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
		<div class="form-buttons">
			<input type="submit" value="Send" class="btn btn-primary">
			<a href="{%url 'dwitter:userlogin' %}"  class="btn btn-outline">Cancel</a>
		</div>
	</form>
	</div>
{%endblock content%}

dwitter/templates/dwitter/password_reset_complete.html
{%extends 'base.html'%}

{%block content%}

<div class="card center">
	<p>Your password has been changed successfully. Please <a href="{% url 'dwitter:userlogin' %}">Login</a></p>
</div>
 	
{%endblock content%}

dwitter/templates/dwitter/password_reset_confirm.html
{%extends 'base.html'%}

{%block content%}

<div class="center">
	<form method="post" class="card">
	  {% csrf_token %}
	  <h2>Password Reset Confirm</h2>
	  
	  {% for field in form %}
	    		{{ field.label_tag }} 
	        	{{ field }}
	        	{% if field.errors %}
	        		<small>{{ field.errors|striptags  }}</small> 
	        	{% endif %}
		{% endfor %}
	  
	  
	  <div>
	    <button type="submit" class="btn btn-primary">Reset Password</button>
	  </div>
	</form>
</div>


{%endblock content%}

dwitter/templates/dwitter/password_reset_done.html
{%extends 'base.html'%}

{%block content%}

<div class="center card">
	<h2>Reset Password</h2>
	<p>Please check your inbox and follow the instruction to reset your password.</p>
</div>

{%endblock content%}

dwitter/templates/dwitter/password_reset_email.html
<p>Hi</p>

<p>You're receiving this email because you requested a password reset for your user account at {{domain}}/</p>

<p>Please click the following link to reset your password:</p>

{{ protocol }}://{{ domain }}{% url "password_reset_confirm" uidb64=uid token=token %}

<p>Thanks</p>
<p>Todo App Team</p>

dwitter/templates/dwitter/profile.html
<!-- dwitter/templates/dwitter/profile.html -->

{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

<div class="column">

    <div class="block">
    <h1 class="title is-1">
        {{profile.user.username|upper}}'s Posts
    </h1>
    </div>

    <div class="card" >
        <div class="card-image" style=" display: flex;
        justify-content: center; padding:20px; ">
          <figure class="imgclass" >
            <img class="is-rounded"
              src="{% static profile.profile_pic.url %}"
              alt="Placeholder image"
              style="height:200px; weight:200px "
            />
          </figure>
        </div>
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                <img
                  src="{% static profile.profile_pic.url %}"
                  alt="Placeholder image"
                />
              </figure>
            </div>
            <div class="media-content">
              <p class="title is-4">{{profile.user.first_name}} {{profile.user.last_name}}</p>
              <p class="subtitle is-6">@{{profile.user.username}}</p>
            </div>
          </div>
      
          <div class="content">
            {{profile.bio}}
            
            <br />
            Wish Me at {{profile.dob}}

            {% if profile.is_online %}
            Online
            {% else %}
            Offline
            {% endif %}

          </div>
        </div>
      </div>


    <form method="post" style="margin:20px">
        {% csrf_token %}
    <div class="buttons has-addons">
        {% if profile in user.profile.follows.all %}
            <button class="button is-success is-static">Follow</button>
            <button class="button is-danger" name="follow" value="unfollow">
                Unfollow
            </button>
        {% else %}
            <button class="button is-success" name="follow" value="follow">
                Follow
            </button>
            <button class="button is-danger is-static">Unfollow</button>
        {% endif %}
    </div>
</form>
<div class="content">
    {% if profile in user.profile.follows.all %}

    {% for dweet in profile.user.dweets.all %}
        <div class="box">
            <div class="title" style="font-size:xxx-large">  {{dweet.title}}</div>
                <div class="title" style="font-size:0.9em; font-weight:400;">  {{ dweet.body }} </div>
               

                <div class="imgclass" style="background-Color:#F5ECAD; height:350px; weight:100%; padding:20px; outline: solid 1px black;
                display: flex;
                justify-content: center; ">
               
                    <img class="img" src="{% static dweet.post.url %}" alt="post pic" style="height:300px; weight:300px;outline: solid 1px black;" >
                </div> 
        </div>
    {% endfor %}
    
    {% else %} 
    {% for dweet in profile.user.dweets.all %}
    <div class="box">
        <div class="title" style="font-size:xxx-large">  {{dweet.title}}</div>
        <div class="title" style="font-size:0.9em; font-weight:400;">  {{ dweet.body | truncatechars:5 }} </div>
        Follow for more....
    </div>
    {% endfor %}
    {% endif %}
</div>
</div>


<div class="column is-one-third">

    <div class="block">
        <a href="{% url 'dwitter:profile_list' %}">
            <button class="button is-dark is-outlined is-fullwidth">
                All Profiles
            </button>
        </a>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} follows:
        </h3>
        <div class="content">
            <ul>
            {% for following in profile.follows.all %}
                <li>
                    <a href="{% url 'dwitter:profile' following.id %}">
                        {{ following }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

    <div class="block">
        <h3 class="title is-4">
            {{profile.user.username}} is followed by:
        </h3>
        <div class="content">
            <ul>
            {% for follower in profile.followed_by.all %}
                <li>
                    <a href="{% url 'dwitter:profile' follower.id %}">
                        {{ follower }}
                    </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    </div>

</div>

{% endblock content %}

dwitter/templates/dwitter/profile_list.html
<!-- dwitter/templates/dwitter/profile_list.html -->

{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}

<div class="column">

{% for profile in profiles %}

    <div class="block">
      
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <figure class="image is-48x48">
                
                <img src="{% static profile.profile_pic.url %}"
                     alt="Placeholder image">
              </figure>
            </div>
            <div class="media-content">
              <a href="{% url 'dwitter:profile' profile.id %}">
                <div class="card-content">
                    <!-- ... More card code -->
                    <p class="title is-4">
                      {{ profile.user.username }}
                    </p>
                    <p class="subtitle is-6">
                      @{{ profile.user.username|lower }}
                    </p>
                </div>
            </a>
              
              
            </div>
          </div>
        </div>
        
          
        </a>
      </div>
    </div>

{% endfor %}

</div>

{% endblock content %}

dwitter/templates/dwitter/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block content %}
<style>
  .form{
    color: #EEEEEE
  }
  .box {
    width: 100%;
    padding: 20px;
    position: absolute;
    top: 50%;
    
    background: #3E454C;

    text-align: center;
    transition: 0.25s;
    margin-top: 100px;
    border-radius: 50px;
}

.box input[type="text"],
.box input[type="password"],.box input[type="email"] {
    border: 0;
    background: none;
    
    margin: 20px auto;
    text-align: center;
    border: 2px solid #ffffff;
    padding: 10px 10px;
    width: 250px;
    outline: none;
    color: white;
    border-radius: 24px;
    transition: 0.25s
}

.box h1,p {
    color: white;
    /* text-transform: uppercase; */
    font-weight: 500
}

.box input[type="text"]:focus,
.box input[type="password"]:focus {
    width: 300px;
    border-color: #76ABAE
}

.box input[type="submit"] {
    border: 0;
    background: none;
    display: block;
    margin: 20px auto;
    text-align: center;
    border: 2px solid #40E0D0;
    padding: 14px 40px;
    outline: none;
    color: white;
    border-radius: 24px;
    transition: 0.25s;
    cursor: pointer
}

.box input[type="submit"]:hover {
    background: #40E0D0
}

.forgot {
    text-decoration: underline
}
</style>
<form class="box" method="post" enctype="multipart/form-data">
    {% csrf_token %}
      <h1> Sign Up</h1>
      
        <p> {% render_field userForm.first_name class="form-control" placeholder="First Name" %}</p>
          <p>{% render_field userForm.last_name class="form-control" placeholder="Last Name" %}</p>
            <p> {% render_field userForm.username class="form-control" placeholder="Username" %}</p>
              <p> {% render_field userForm.email class="form-control" placeholder="Email" %}</p>
                <p> {% render_field userForm.password class="form-control" placeholder="Password" %}</p>
                  <p> {% render_field profileForm.bio class="form-control" placeholder="bio" %}</p>
                    <p>{% render_field profileForm.dob class="form-control" placeholder="dob" %}<br></p>
                      <p>{% render_field profileForm.profile_pic class="form-control" placeholder="Profile pic" %}</p>
    
       <input type="submit" name="" value="Create">

  </form>

  {{msg}}
  
{% endblock content %}

dwitter/templates/dwitter/userlogin.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block content %}
<style>
  .box {
    width: 50%;
    padding: 40px;
    position: absolute;
    top: 50%;
    
    background: #3E454C;
    text-align: center;
    transition: 0.25s;
    margin-top: 100px;
    left: 30%;

    border-radius: 50px;
}

.box input[type="text"],
.box input[type="password"] {
    border: 0;
    background: none;
    display: block;
    margin: 20px auto;
    text-align: center;
    border: 2px solid #ffffff;
    padding: 10px 10px;
    width: 250px;
    outline: none;
    color: white;
    border-radius: 24px;
    transition: 0.25s
}

.box h1 {
    color: white;
    /* text-transform: uppercase; */
    font-weight: 500
}

.box input[type="text"]:focus,
.box input[type="password"]:focus {
    width: 300px;
    border-color: #76ABAE
}

.box input[type="submit"] {
    border: 0;
    background: none;
    display: block;
    margin: 20px auto;
    text-align: center;
    border: 2px solid #40E0D0;
    padding: 14px 40px;
    outline: none;
    color: white;
    border-radius: 24px;
    transition: 0.25s;
    cursor: pointer
}

.box input[type="submit"]:hover {
    background: #40E0D0
}

.forgot {
    text-decoration: underline
}
</style>
<div class="container">
<form class="box" method="post">
    {% csrf_token %}
      <h1>Customer Login</h1>
      
                 {% render_field form.username class="form-control" placeholder="Username" autocomplete="off" %}
                 {% render_field form.password class="form-control" placeholder="Password" %}
       <input type="submit" name="" value="Login" >
       <a href={%url 'password_reset' %}  class="btn btn-outline">Forgot Password</a>

  </form>
</div>
  
<!--{%url 'dwitter:password_reset' %}-->
  {% endblock content %}