dwitter/urls.py
# dwitter/urls.py

from django.urls import path
from django.urls import reverse_lazy
from .views import dashboard, profile_list,profile,signup,userlogin,base,afterlogin_view,adddweet
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.views import ( 
    PasswordResetView, 
    PasswordResetDoneView, 
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from chatApp.views import chating


app_name = "dwitter"

urlpatterns = [
    path("", base, name="base"),
    path("dashboard", dashboard, name="dashboard"),
    path("afterlogin", afterlogin_view, name="afterlogin"),
    path("profile_list/", profile_list, name="profile_list"),
    path("profile/<int:pk>", profile, name="profile"),
    path("signup",signup,name="signup"),
    path("userlogin",LoginView.as_view(template_name='dwitter/userlogin.html'),name="userlogin"),
    path("userlogout",LogoutView.as_view(template_name='base.html'),name="logout"),
    path('password_reset/', 
        PasswordResetView.as_view(
            template_name='dwitter/password_reset.html',
            html_email_template_name='dwitter/password_reset_email.html'
        ),
        
        name='password_reset'
    ),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='dwitter/password_reset_done.html'),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='dwitter/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password_reset_complete/',PasswordResetCompleteView.as_view(template_name='dwitter/password_reset_complete.html'),name='password_reset_complete'),
    
    path('adddweet',adddweet,name="adddweet"),
    
    
    
]

social/urls.py
from django.contrib import admin
from django.urls import path,include
from chatApp.views import chating,group_chat,createGroup
from videoApp.views import lobby,room,getToken

urlpatterns = [
    path('', include("dwitter.urls")),
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls')),
    #Chat
    path('chating/',chating,name='chating'),
    path('group/',group_chat,name='group_chat'),
    #~~~~~~
    path('lobby',lobby,name="lobby"),
    path('room/',room,name="room"),
    path('getToken/',getToken,name="get_token"),
    path('creategroup/',createGroup,name="createGroup")
    
]

dwitter/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField(
        "self",
        related_name="followed_by",
        symmetrical=False,
        blank=True
    )
    dob=models.DateField(blank=True,null=True)
    bio=models.CharField(max_length=50)
    profile_pic= models.ImageField(upload_to='static/profile_pic/userprofilepic/',null=True,blank=True)
    is_online=models.BooleanField(default=False)
    def __str__(self):
        return self.user.username
    
@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        #Profile.objects.create(user=instance)
        user_profile=Profile(user=instance) 
        user_profile.save()
        print("success")
        user_profile.follows.add(user_profile)
        user_profile.save()
        
class Dweet(models.Model):
    user = models.ForeignKey(
        User, related_name="dweets", on_delete=models.DO_NOTHING
    )
    title= models.CharField(max_length=100)
    post= models.ImageField(upload_to='static/post/',null=True,blank=True)
    body = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    likedby = models.ManyToManyField(User,related_name="likes",blank=True)
    
    def __str__(self):
        return (
            f"{self.user} "
            f"({self.created_at:%Y-%m-%d %H:%M}): "
            f"{self.body[:30]}..."
        )


class Comment(models.Model):
    dweet=models.ForeignKey(Dweet,related_name="comments",on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, related_name="comments", on_delete=models.DO_NOTHING
    )
    body = models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return (
            f"{self.user} "
            f"({self.created_at:%Y-%m-%d %H:%M}): "
            f"{self.body[:30]}..."
        )

dwitter/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class SignUpForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','email','username','password']
        widgets = {
        'password': forms.PasswordInput()
        }
        
class ProfileForm(forms.ModelForm):
    class Meta:
        model=models.Profile
        fields=['dob','bio','profile_pic']
        widgets = {
    'dob': forms.DateInput(
        format=('%Y-%m-%d'),
        attrs={'class': 'form-control', 
               'placeholder': 'Select a date',
               'type': 'date'
              }),
}
        
class DweetForm(forms.ModelForm):
    class Meta:
        model=models.Dweet
        fields=['body','post','title']
        widgets = {
        'body': forms.Textarea(attrs={'rows': 3, 'cols': 30})
        }
        


class CommentForm(forms.Form):
    dweetid=  forms.CharField(max_length=20)
    body = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'cols': 30}))

dwitter/views.py
# dwitter/views.py

from django.shortcuts import render,redirect
from .models import Profile,Dweet,Comment
from django.contrib.auth.decorators import login_required
from . import forms,models
from django.http import HttpResponseRedirect,HttpResponse
from django.dispatch import receiver
from django.contrib.auth.signals import user_logged_in,user_logged_out
from django.contrib.auth.models import User


@receiver(user_logged_in)
def got_online(sender,user,request,**kwargs):
    print(user)
    """user.profile.is_online = True
    user.save()"""
    curruser=Profile.objects.get(user=user)
    curruser.is_online=True
    curruser.save()
    
    print("HEllo",user.profile.is_online,user.username,curruser.is_online)

@receiver(user_logged_out)
def got_offline(sender,user,request,**kwargs):
    curruser=Profile.objects.get(user=user)
    curruser.is_online=False
    curruser.save()
    print("bye")
    print("bye",user.profile.is_online,user.username,curruser.is_online)
    

def signup(request):
    profiles=Profile.objects.all()
    usernames=[x.user.username for x in profiles]
    
    userForm=forms.SignUpForm()
    profileForm=forms.ProfileForm()
    mydict={'userForm':userForm,'profileForm':profileForm,'usernames':usernames}
    if request.method=='POST':
        print("post")
        userForm=forms.SignUpForm(request.POST)
        profileForm=forms.ProfileForm(request.POST,request.FILES)
        if userForm.is_valid() and profileForm.is_valid():
            
            user=userForm.save()
            user.set_password(user.password)
            user.save()
            user_profile=Profile.objects.get(user=user)
            print(user_profile)
            print(profileForm.cleaned_data['dob'])
            user_profile.dob=profileForm.cleaned_data['dob']
            user_profile.bio=profileForm.cleaned_data['bio']
            user_profile.profile_pic=profileForm.cleaned_data['profile_pic']
            
            user_profile.save()
            """customer=profileForm.save(commit=False)
            customer.user=user
            customer.save()"""
        else:
            mydict['msg']="A user with that username already exist"
            return render(request,'dwitter/signup.html',context=mydict)

            
    
        return HttpResponseRedirect('userlogin')
    return render(request,'dwitter/signup.html',context=mydict)

def userlogin(request):
    print(request.user)
    return render(request, "dwitter/userlogin.html")
def afterlogin_view(request):
    """curruser=Profile.objects.get(user=request.user)
    curruser.is_online=True
    curruser.save()"""
    return redirect('dashboard')
@login_required()
def dashboard(request):
    if request.method == "POST":
        data = request.POST
        action = data.get("likebtn")
        print(action)
        if action!=None:
            arr=action.split('-')
            did=arr[0]
            act=arr[1]
            dweet=Dweet.objects.get(id=did)
            if act == "like":
                dweet.likedby.add(request.user)
            elif act == "unlike":
                dweet.likedby.remove(request.user)
            dweet.save()
        # create a form instance and populate it with data from the request:
        form = forms.CommentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            #user_profile=Dweet.objects.get(pk=pk)
            #print(user_profile)
            #print("hello")
            #print(Dweet.objects.get(pk=form.cleaned_data['dweetid']))
            comment=Comment.objects.create(dweet=Dweet.objects.get(pk=form.cleaned_data['dweetid']),user=request.user,body=form.cleaned_data['body'])
            #print(form.cleaned_data['body'])
            comment.save()
            # redirect to a new URL:
            return HttpResponseRedirect("dashboard")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.CommentForm()
    print(request.user)
    profiles=Profile.objects.all()
    mails=[x.user.email for x in profiles]
    
    dct={"mails":mails,"form":form}
    return render(request, "dwitter/dashboard.html",context=dct)
@login_required()
def profile_list(request):
    profiles = Profile.objects.exclude(user=request.user)
    return render(request, "dwitter/profile_list.html", {"profiles": profiles})

def base(request):
    if request.user.is_authenticated:
        HttpResponseRedirect('dwitter/dashboard')
    return render(request,"base.html")
@login_required()
def profile(request, pk):
    """below section has to deleted"""
    """if not hasattr(request.user, 'profile'):
        missing_profile = Profile(user=request.user)
        missing_profile.save()"""

    
    
    profile = Profile.objects.get(pk=pk)
    if request.method == "POST":
        current_user_profile = request.user.profile
        data = request.POST
        action = data.get("follow")
        if action == "follow":
            current_user_profile.follows.add(profile)
        elif action == "unfollow":
            current_user_profile.follows.remove(profile)
        current_user_profile.save()
    print(profile.is_online,profile.user.username,request.user.username,request.user.profile.is_online)
    return render(request, "dwitter/profile.html", {"profile": profile})

@login_required()
def adddweet(request):
    dweetForm=forms.DweetForm()
    if request.method=='POST':
        dweetForm=forms.DweetForm(request.POST, request.FILES)
        if dweetForm.is_valid():
            dweet=dweetForm.save(commit=False)
            dweet.user=request.user
            dweet.save()
            #dweetForm.save()
            """dweet=Dweet.objects.get(body=dweetForm.cleaned_data['body'])
            print(dweet)
            dweet.user=request.user
            dweet.save()"""
        return HttpResponseRedirect('dashboard')
    
    return render(request, "dwitter/dweet.html",{'dweetForm':dweetForm})


@login_required()
def addComment(request,pk):
    # if this is a POST request we need to process the form data
    if request.method == "POST":
        # create a form instance and populate it with data from the request:
        form = forms.CommentForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            #user_profile=Dweet.objects.get(pk=pk)
            #print(user_profile)
            comment=Comment.objects.create(dweet=pk,user=request.user,body=form.cleaned_data['body'])
            print(form.cleaned_data['body'])
            comment.save()
            # redirect to a new URL:
            return HttpResponseRedirect("dashboard")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = forms.CommentForm()

    return render(request, "dashboard.html", {"form": form})

dwitter/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    
    <title>Social</title>
    <style>
      body{
  
        height:91vh;
      }
        .bgcolor{
            background: #00ADB5;
          
            color:#074173
        }
    </style>
</head>
<body >
    <section class="hero is-small bgcolor mb-4">
        <div class="hero-body">
            
            



            <nav class="navbar" role="navigation" aria-label="main navigation">
                <div class="navbar-brand" style="padding-right:50px">
                    <h1 class="title is-1" style="color:#222831;">Social</h1>
                </div>
              
                <div id="navbarBasicExample" class="navbar-menu" >
                  
              
                  <div class="navbar-end">
                    
                      <a class="navbar-item" href="{% url 'dwitter:base' %}">
                        Home
                      </a>

                      {% if request.user.is_authenticated%}
                      <a class="navbar-item" href="{%url 'dwitter:profile' request.user.profile.id %}">
                        My Profile
                      </a>
                      {%endif%}
                      <a class="navbar-item" href="{%url 'dwitter:profile_list' %}">
                        Explore
                      </a>

                      <a class="navbar-item" href="{%url 'chating' %}">
                        Chat
                      </a>

                      <a class="navbar-item" href="{%url 'group_chat' %}">
                        Groups
                      </a>

                      <a class="navbar-item" href="{%url 'lobby' %}">
                        Meet
                      </a>
                
                      <div class="navbar-item has-dropdown is-hoverable">
                        <a class="navbar-link">
                          Post
                        </a>
                
                        <div class="navbar-dropdown">
                          <a class="navbar-item" href="{%url 'dwitter:dashboard' %}">
                            Show Post
                          </a>
                          <a class="navbar-item is-selected" href="{%url 'dwitter:adddweet' %}">
                            Create Post
                          </a>
                          <a class="navbar-item">
                            Contact
                          </a>
                          <hr class="navbar-divider">
                          <a class="navbar-item">
                            Report an issue
                          </a>
                        </div>
                      </div>
                    




                    <div class="navbar-item">
                      <div class="buttons">
                        {% if request.user.is_authenticated%}
                        <a class="button is-light" href="/logout">
                          Log Out
                        </a>
                        
                        {% else %}
                        <a class="button is-primary" style="background-color:#393E46" href="{%url 'dwitter:signup' %}">
                          <strong>Sign up</strong>
                        </a>


                        <a class="button is-light" href="{%url 'dwitter:userlogin' %}">
                          Log in
                        </a>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>
              </nav>




        </div>
    
    </section>
                <div class="container">
                    <div class="columns">
        {% block content %}
        
        {% endblock content %}
    </div>
</div>

</body>
</html>